# Generated by Django 5.2.5 on 2025-11-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nailsite', '0003_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
